### ISSUE TITLE
How does one know if markdown is in Blueprint API format?

### ISSUE THREAD

**Issue by streamich** [apiaryio/api-blueprint#143]
How does one know if markdown is in Blueprint API format? For example, say I have an incoming markdown file. If the file is in Bluepring API format I should render it as and API, otherwise I render it as a standard Markdown HTML. But how do I know if the markdown is in Blueprint API format?

**Comment by pksunkara** [comment]
@streamich We try to parse the incoming markdown file and generate the API Blueprint AST assuming that the given file is an API Blueprint file. You can probably look at the generated AST and guess if a file is an API Blueprint or not. But it is not always deterministic since the normal markdown file can use API Blueprint keywords. Other than that, there are no ways to identify a API Blueprint file.

Please remember that, every API Blueprint file is a markdown file where as not every markdown file is an API Blueprint file.

**Comment by zdne** [comment]
>  But how do I know if the markdown is in Blueprint API format?

You can't really.  Similarly as you can't distinguish plain text from markdown. The only way is to get the metadata (e.g. `Content-Type`) with the file.

In the case of `Content-Type` or `Accept` HTTP headers the value for API Blueprint Markdown should be `text/vnd.apiblueprint+markdown`.

**Comment by zdne** [comment]
Note the `FORMAT: 1A` is Apiary-specific metadata and it is not required in API Blueprints outside of Apiary. In a future it will be removed from Apiary as well, so I wouldn't really rely on it.

**Comment by streamich** [comment]
May API blueprints should have their file extensions? Like minified JS files have `.min.js`, API blueprints could be something like `.api.md`.

**Comment by zdne** [comment]
We are using `.apib` at Apiary. But I like the `.api.md` as well – this allows you to benefit from GitHub rendering of markdown files. So while we are using `apib` I would say sticking with `api.md` is a good alternative.

**Comment by zdne** [comment]
To wrap up this issue – the correct approach is to look at the file [media type](https://github.com/apiaryio/api-blueprint#media-type) – it should be `text/vnd.apiblueprint+markdown` for every API Blueprint version to-date. 

Please reopen if a further clarification is needed.
