### ISSUE TITLE
Navigation inside the editor

### ISSUE THREAD

**Issue by mallowigi** [apiaryio/api-blueprint#150]
Not sure if this is the right place to put this, but I wondered if there is plans to navigate inside the editor, the same way we can navigate inside the documentation (e.g. clicking on a section will scroll to the referenced section)

**Comment by honzajavorek** [comment]
@mallowigi Unfortunately, we do not have such navigation in the Apiary editor currently, but it is definitely planned to improve working with larger blueprints and the editor in overall.

Thank you for mentioning it though, because such requests let us to feel that it is really needed and awaited. Good user feedback is sometimes more powerful fuel for writing code than coffee! :coffee: 

By the way, this is an API Blueprint spec repo. If you have more ideas, you can share them at http://support.apiary.io/. Voting for particular features will get you notified when we complete them or change their status.

**Comment by zdne** [comment]
@mallowigi definitely a good point. Navigation in bigger blueprints needs to be improved. 

We are planning a significant revamp of the Apiary.io editor. It will definitely include some sort of better navigation as well as support for multi-file – #8 

If you want please follow [Apiary on Twitter](https://twitter.com/apiaryio) for updates on this.

Please feel free submit ideas on how this should work either here or directly to [Apiary support](http://support.apiary.io)

Thanks!
