### ISSUE TITLE
Minimum/Maximum values for URI Parameters

### ISSUE THREAD

**Issue by HawkiesZA** [apiaryio/api-blueprint#211]
We'd like to be able to set a minimum value for URI Parameters. Could do something similar for maximum. e.g.:

+ limit (optional, integer, `10`)
        Limit the number of results to return. If omitted all results in the period are returned.
    + Minimum: (`0`, exclusive)
    + Maximum: (`10`, inclusive)

Running it through snowcrash should then yield something like:

{
    "name": "limit",
    "description": "Limit the number of results to return. If omitted all results in the period are returned.",
    "type": "integer",
    "required": false,
    "default": "",
    "example": "10",
    "values": [],
    "minimum": 0,
    "exclusiveMinimum": true,
    "maximum": 10,
    "exclusiveMaximum": false
}

**Comment by zdne** [comment]
Hey @HawkiesZA 

This is definitely planned as part of [MSON validation](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#46-validations). Since Parameter's description is converging to MSON (and eventually should become the same) it should get to it as well. 

However I am afraid in the interim period the only way is to write this intent (limits / validation) into parameter's description. 

Any contribution to syntax and / or implementation is highly appreciated!

**Comment by zdne** [comment]
I have just proposed an RFC that should introduce the complete MSON syntax to URI parameters. This is indirectly solving this issue as MSON should eventually introduce value validation. Please see and comment on https://github.com/apiaryio/api-blueprint-rfcs/pull/3
