### ISSUE TITLE
console error when using .(dot) in parameter list

### ISSUE THREAD

**Issue by meprateek1986** [apiaryio/api-blueprint#223]
My apiary documentation is on http://docs.prateek2.apiary.io/
There clicking on "project" api and "get projects by criteria" then I get below console error
```
Uncaught Error: Invalid Variable Name "members.userId" in "{?id,name,startdate,enddate,status,externalSystem,members.userId}"
```

We are using Apiary for our production purpose but right now as it is failing we are not able to publish the latest apis. Please help ASAP.

**Comment by honzajavorek** [comment]
@meprateek1986 

At first sight it looks like problem in your URI Template (that's the `/project{?id,name,startdate,enddate,status,externalSystem,members.userId}` part). It shouldn't make the documentation throw errors into browser console, that's for sure, but the good news is that the root of your problem is probably something you can fix in your blueprint.

We implement URI Templates exactly according to the [RFC 6570 standard](https://tools.ietf.org/html/rfc6570). The standard doesn't allow you to have dot character in your template (you have it in the `members.userId` parameter), because it has a special meaning (see section [3.2.5](https://tools.ietf.org/html/rfc6570#section-3.2.5)).

The standard itself doesn't give us any way how to escape characters and we're still about to decide a strategy how to deal with the issue on parser level (https://github.com/apiaryio/snowcrash/issues/61), so the unfortunate outcome is that you need to avoid having dots in names of your parameters for now.

-----------------

Please mind this is issue tracker of the open source *API Blueprint* format in which you write your documentation. *Apiary* is set of tools as a service around this format. To get the best and as immediate as possible support from Apiary, it's usually better to write into the in-app chat:

![support](https://cloud.githubusercontent.com/assets/283441/8542179/03429a58-2494-11e5-9ef4-0fc796eafdf0.png)

**Comment by honzajavorek** [comment]
@meprateek1986 Sorry for initial confusion, I just noticed this is already present in the Apiary in-app support chat and also in our internal issue tracker. I'll cross-link everything and we'll keep you updated on this.

**Comment by honzajavorek** [comment]
@meprateek1986 I explored the https://github.com/apiaryio/snowcrash/issues/61 issue further and I see there should be a workaround. As stated in https://github.com/apiaryio/snowcrash/issues/58, it should be able to smuggle reserved characters into the URI Template by [percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding). That's the preferred way to escape. Sorry for turning you down at first!

As dot is [*unreserved* character](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_unreserved_characters) in normal URLs and as such it is not getting encoded by regular tools for percent-encoding (it's discouraged to encode unreserved characters) it's a bit tricky to get it's `%` variant, but [this online tool](http://2tap.com/javascript-percent-encoder/) helped me to get through the problem and the magic result is `%2e`.

If you write

```
/project{?id,name,startdate,enddate,status,externalSystem,members%2euserId}
```

in your blueprint, everything should work as intended. I just tried it out in sample Apiary project and it seemed to be displayed correctly, third column opened without a problem. Would this be a solution for you?

**Comment by meprateek1986** [comment]
It worked. Thanks Honza :)

**Comment by honzajavorek** [comment]
@meprateek1986 Awesome! I'm glad I could help!

**Comment by beetlerom** [comment]
We are using the `.` character in our query parameters in our APIs. While the workaround provided here works, it's a bit of a shame that after 2 years the RFC is still not correctly implemented. 

Any chance to put this issue on the road-map anytime soon?

**Comment by marco-cdlv** [comment]
same issue it's being displayed as expected but when I execute the rest call to production option it throws me 400 error code due to the executed endpoint was changed from /api/v1/parent%2e.name to /api/v1/Parent%252eName.... why is changed from %2e to %252e??
