### ISSUE TITLE
How to deal with versioned API's

### ISSUE THREAD

**Issue by ThorstenHans** [apiaryio/api-blueprint#258]
I've versioned APIs to document. The API is being versioned based on a HTTP Header in order to keep request URLs restful.

How would you document such  an API ? would you include all versions in a single blueprint or create a new blueprint for each and every API release?

**Comment by zdne** [comment]
That is a very good question @ThorstenHans ! 

Generally, I do suggest to have separate versions of blueprints for different version of APIs unless:

1. you are using HATEOAS
2. you are relying on media-type versioning

Check the awesome article on this topic by Mark Nottingham – https://www.mnot.net/blog/2011/10/25/web_api_versioning_smackdown

Note when it comes to separate blueprint versions you can use GitHub to help with this since your blueprint is just a versioned file in a repo. 

Does this help?

**Comment by fesor** [comment]
I like the idea of using separate files for each version, but this would probably break DRY. Includes partially solves that problem but...

**Comment by hendrikmaus** [comment]
I am also thinking on the topic and strive to find a good solution. What we currently do at @trivago, is to keep the documentation for legacy v1 and v2 completely separate. But this will only work as long as we do not version any endpoint inside v2.

We do use hypermedia and we do version using the accept header. @zdne I guess you meant the same with:

> you are relying on media-type versioning

I think api blueprint itself is on the right track with moving `+ Headers` into the respective payload section.
So instead of:

```apib
### Retrieve a Message [GET]
This action has **two** (...)

+ Headers

        X-My-Message-Header: 42

+ Response 200 (text/plain)

        Hello World!
```

we'll do this:

```apib
### Retrieve a Message [GET]
This action has **two** (...)

+ Response 200 (text/plain)

    + Headers

            X-My-Message-Header: 42

    + Body

            Hello World!
```
Like the [example in the apib repo](https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/05.%20Responses.md) already states.

This already let's us define headers per response.

What we would need to change, in order to support versioning at this state, is to allow multiple responses for the same endpoint. Currently, the apib parser will complain about this:

```apib
### Retrieve a Message [GET]
This action has **two** (...)

+ Response 200 (application/json)

    + Headers

            Accept: application/vnd.trivago.yourwebservice+json;version=1

    + Body

            { "message": "Hello v1" }

+ Response 200 (application/json)

    + Headers

            Accept: application/vnd.trivago.yourwebservice+json;version=2

    + Body

            { "message": { "content": "Hello v2" } }
```

@zdne do you have thoughts on this?

**Comment by zdne** [comment]
@hendrikmaus isn't what you want 

```apib

## Message [/message]
### Retrieve a Message [GET]

+ Response 200 (application/vnd.trivago.yourwebservice+json;version=1)

        { "message": "Hello v1" }

+ Response 200 (application/vnd.trivago.yourwebservice+json;version=2)

        { "message": { "content": "Hello v2" } }

```

This way you wont get warning.

**Comment by zdne** [comment]
@hendrikmaus 

or in detail (complete request response  transaction examples): 

```apib

## Message [/message]
### Retrieve a Message [GET]

+ Request V1
    + Headers

            Acccept: application/vnd.trivago.yourwebservice+json;version=1

+ Response 200 (application/vnd.trivago.yourwebservice+json;version=1)

        { "message": "Hello v1" }


+ Request V1
    + Headers

            Acccept: application/vnd.trivago.yourwebservice+json;version=2

+ Response 200 (application/vnd.trivago.yourwebservice+json;version=2)

        { "message": { "content": "Hello v2" } }
```

**Comment by hendrikmaus** [comment]
@zdne thank's for throwing some light in my dark :+1: 
I haven't seen it; must have had my blinders on :horse: 

@ThorstenHans does this also answer your question?

**Comment by ThorstenHans** [comment]
:+1: yep, I'm fine with that
