### ISSUE TITLE
Adding a boolean to attributes removes the name of the boolean on nested objects.

### ISSUE THREAD

**Issue by gsigler2** [apiaryio/api-blueprint#352]
```
+ Attributes
        + anObject (object) - Some Text
            + anArray (array) - Some Text
                + aString: someTextInAString  - Some Text
                + aBoolean:  false (boolean) - Some Text
```
![booleansdonotworkright](https://cloud.githubusercontent.com/assets/9119953/18366085/820ba98e-75d2-11e6-8d11-b50457c55a85.PNG)

I would expect booleans to show the name and value just like strings arrays and objects and booleans at higher levels.

**Comment by kylef** [comment]
Hi @gsigler2,

What you have described is equivalent to the following in JSON:

```json
[
  "aString: someTextInAString",
  false
]
```

The value of your boolean is set to `aBoolean:  false` which translates to false because it is not true.

You cannot have key/value pairs directly inside an array. I expect you meant to instead wrap them in a object. Which you can do with the following syntax:

```apib
+ Attributes
    + anObject (object) - Some Text
        + anArray (array) - Some Text
             + (object)
                 + aString: someTextInAString  - Some Text
                 + aBoolean: false (boolean) - Some Text
```

**Comment by gsigler2** [comment]
Ahh duh. makes sense.
