### ISSUE TITLE
Need multiple actions of same HTTP verb on same resource (but different request content-type)

### ISSUE THREAD

**Issue by jrep** [apiaryio/api-blueprint#55]
We have an API that provides two roughly equivalent forms for POST to the same URL. The key difference is the Content-Type: of the request: it accepts either application/json or text/dns (RFC-4207). The two request forms are closely related, but it would be an exaggeration to say they're merely direct translations one of the other.

Legacy Blueprint allows us [to say this](https://developer.akamai.com/api/luna/config-edns/reference.html). The FORMAT:1A editor ignores it (only displays one of the two).

Is there some way I can achieve this?

**Comment by foxx** [comment]
Although an endpoint can have multiple transaction examples, as seen in [apiaryio/snowcrash#53](https://github.com/apiaryio/snowcrash/issues/53) these don't render out very cleanly in Apiary.

Take the following example... 

You have `/oauth2/authorize`, which by specification will handle various different scenarios (such as getting an access token from refresh, or generating a token from password, etc). Having these merged into a single action on the API docs is very hard for the reader to understand, instead it's easier for the user to have multiple endpoints such as "Refresh access token" and "Authenticate User" in the side menu. However this is not possible because you cannot specify the same method/URL combination twice.

**Comment by vitaly-zdanevich** [comment]
I see incorrect syntax highlight - see the color of `Body`:

![screen shot 2017-02-22 at 16 06 36](https://cloud.githubusercontent.com/assets/3514015/23212717/14791fa8-f919-11e6-8163-2d763ccb8821.png)
